web:
  image: iporaitech/pwr2-docker:latest
  command: /sbin/my_init --enable-insecure-key #enable insecure key for dev
  # volumes:
  #   - .:/home/app/webapp
  links:
    - db
  ports:
    - "4000:4000" # use this port for HTTP_PORT
    - "4443:4443" # use this port for HTTPS_PORT
    - "2222:22" # use this port to access container via "normal" SSH
    - "44369:4369" # use this port to config SSH forward to distributed node
    - "9001:9001" # use this port when starting webapp  as distributed node
  environment:
    MIX_ENV: "${MIX_ENV}"
    NODE_ENV: "${NODE_ENV}"

    # Webapp
    PWR2_HTTP_PORT: "${PWR2_HTTP_PORT}"
    PWR2_HTTPS_PORT: "${PWR2_HTTPS_PORT}"

    # Core
    PWR2_CORE_DB: "${PWR2_CORE_DB}"
    PWR2_CORE_DB_HOST: "${PWR2_CORE_DB_HOST}"
    PWR2_CORE_DB_PORT: "${PWR2_CORE_DB_PORT}"
    PWR2_CORE_DB_USER: "${PWR2_CORE_DB_USER}"
    PWR2_CORE_DB_PASSWORD: "${PWR2_CORE_DB_PASSWORD}"
    PWR2_CORE_TEST_DB: "${PWR2_CORE_TEST_DB}"
    PWR2_CORE_GRAPHQL_URL: "${PWR2_CORE_GRAPHQL_URL}"

    # StarWars
    PWR2_STAR_WARS_GRAPHQL_URL: "${PWR2_STAR_WARS_GRAPHQL_URL}"

    # Mailer
    PWR2_MAILER_SERVER: "${PWR2_MAILER_SERVER}"
    PWR2_MAILER_USERNAME: "${PWR2_MAILER_USERNAME}"
    PWR2_MAILER_PASSWORD: "${PWR2_MAILER_PASSWORD}"
  volumes_from:
    - mix_deps

db:
  image: postgres:9.4.4
  ports:
    - "55432:5432" # use this port to access Postgres from outside of the container.

mix_deps:
  image: iporaitech/pwr2-docker:latest
  volumes:
    - /home/app/mix_deps
